// created by manually running jsonata: $.results[0].result.data.dsr.DS[0].PH[0].DM0.C[0]

module.exports.districts = [
    "Bratislava",
    "Prešov",
    "Košice",
    "Bardejov",
    "Prievidza",
    "Námestovo",
    "Nitra",
    "Žilina",
    "Tvrdošín",
    "Martin",
    "Trnava",
    "Sabinov",
    "Čadca",
    "Banská Bystrica",
    "Liptovský Mikuláš",
    "Trenčín",
    "Ružomberok",
    "Michalovce",
    "Poprad",
    "Dolný Kubín",
    "Dunajská Streda",
    "Humenné",
    "Nové Zámky",
    "Stará Ľubovňa",
    "Trebišov",
    "Skalica",
    "Spišská Nová Ves",
    "Bánovce nad Bebravou",
    "Košice - okolie",
    "Topoľčany",
    "Senec",
    "Považská Bystrica",
    "Svidník",
    "Senica",
    "Pezinok",
    "Brezno",
    "Galanta",
    "Vranov nad Topľou",
    "Komárno",
    "Malacky",
    "Lučenec",
    "Veľký Krtíš",
    "Ilava",
    "Levoča",
    "Hlohovec",
    "Snina",
    "Kežmarok",
    "Púchov",
    "Stropkov",
    "Partizánske",
    "Piešťany",
    "Myjava",
    "Nové Mesto nad Váhom",
    "Žiar nad Hronom",
    "Sobrance",
    "Zvolen",
    "Levice",
    "Zlaté Moravce",
    "Rimavská Sobota",
    "Kysucké Nové Mesto",
    "Gelnica",
    "Detva",
    "Šaľa",
    "Poltár",
    "Bytča",
    "Revúca",
    "Žarnovica",
    "Rožňava",
    "Medzilaborce",
    "Banská Štiavnica",
    "Turčianske Teplice",
    "Krupina"
];
